# deployment-nginx.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 4 # We want 3 copies of our Pods
  selector:
    matchLabels:
      app: nginx-app # Selector for the Pods managed by this deployment
  template:
    metadata:
      labels:
        app: nginx-app # Labels for the Pods
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
